new tgrub2 generation tool and tcsd verification in tpm_luks

diff --git a/tpm-luks/tpm-luks b/tpm-luks/tpm-luks
--- a/tpm-luks/tpm-luks
+++ b/tpm-luks/tpm-luks
@@ -79,13 +79,13 @@ function wipe_file
 function tpm_enabled
 {
 	if [ ! -e /sys/class/misc/tpm0/device/enabled ]; then
-		echo "Your TPM device driver doesn't appear to be loaded. Please run"
+		echo "ERROR: Your TPM device driver doesn't appear to be loaded. Please run"
 		echo "\`modprobe tpm_tis\` to load the driver and re-run this script"
 		exit 7
 	fi
 
 	if [ ! /sys/class/misc/tpm0/device/enabled ]; then
-		echo "Your TPM is not enabled in your BIOS. Please halt the machine and"
+		echo "ERROR: Your TPM is not enabled in your BIOS. Please halt the machine and"
 		echo "then cold boot into your BIOS to enable the TPM chip."
 		exit 8
 	fi
@@ -96,7 +96,7 @@ function tpm_enabled
 function tpm_owned
 {
 	if [ $(cat /sys/class/misc/tpm0/device/owned) -ne 1 ]; then
-		echo "Your TPM is unowned, please take ownership:"
+		echo "ERROR: Your TPM is unowned, please take ownership:"
 		tpm_takeownership || exit 9
 	fi
 
@@ -105,15 +105,15 @@ function tpm_owned
 
 function tpm_tcsd
 {
-        tpm_version &> /dev/null
-        RC=$?
-        if [ $RC -ne 0 ]; then
-                echo "ERROR: The 'tcsd' service is not started. Please run 'tcsd' and"
-                echo "re-run this script."
-                exit 40
-        fi
-
-        return 0
+	tpm_version &> /dev/null
+	RC=$?
+	if [ $RC -ne 0 ]; then
+		echo "ERROR: The 'tcsd' service is not started. Please run 'tcsd' and"
+		echo "re-run this script."
+		exit 40
+	fi
+	
+	return 0
 }
 
 #
