new -n option to disable script execution in tpm-luks-init and tpm-luks-update

diff --git a/tpm-luks/tpm-luks-update b/tpm-luks/tpm-luks-update
--- a/tpm-luks/tpm-luks-update
+++ b/tpm-luks/tpm-luks-update
@@ -6,6 +6,26 @@
 #
 CONF=/etc/tpm-luks.conf
 NVPERMSFILE=$(mktemp /tmp/${0##*/}-XXXXXX)
+NO_SCRIPT=0
+
+function usage
+{
+        echo "usage ${0##*/}: [options]"
+        echo -e "  -n                 no script execution"
+        echo -e "  -h                 help"
+}
+
+while getopts "nh" opt; do
+        case $opt in
+        n)
+                NO_SCRIPT=1
+        *)
+                usage
+                exit 255
+                ;;
+        esac
+done
+
 
 function cleanup
 {
@@ -36,12 +56,12 @@ if [ $NUM_UNIQUES -ne $NUM_DEVICES ]; then
 fi
 
 for d in $(seq 0 $NUM_DEVICES); do
-	echo "Generating PCR values for ${DEVICES[$d]}..."
-	if [ -x ${SCRIPTS[$d]} ]; then
+	if [ -x ${SCRIPTS[$d]} -a ${NO_SCRIPT} -eq 0 ]; then
+		echo "Generating PCR values for ${DEVICES[$d]}..."
 		${SCRIPTS[$d]} -o ${NVPERMSFILE}
 		if [ $? -ne 0 ]; then
 			echo "${SCRIPTS[$d]} has failed."
-			continue
+			exit 2
 		fi
 	fi
 
@@ -52,14 +72,10 @@ for d in $(seq 0 $NUM_DEVICES); do
 		tpm-luks -m -i ${INDEXES[$d]} -d ${DEVICES[$d]}
 	fi
 	if [ $? -ne 0 ]; then
-		rm -f ${NVPERMSFILE}
-		continue
+		echo "ERROR: update failed. Aborting."
+		exit 3
 	fi
 	[ -f ${NVPERMSFILE} ] && rm -f ${NVPERMSFILE}
-
-	#echo "# The following line generated by tpm-luks-update" >> ${CONF}
-	#echo "${DEVICES[$d]}:${NEWINDEX}:${SCRIPTS[$d]}" >> ${CONF}
-	#echo "Success. Updated ${CONF} for index ${INDEXES[$d]}."
 done
 
 exit 0
