fix scripts: check for different indexes + allow '-' scripts + replace intead of migrate NVRAM

diff --git a/tpm-luks/tpm-luks-init b/tpm-luks/tpm-luks-init
--- a/tpm-luks/tpm-luks-init
+++ b/tpm-luks/tpm-luks-init
@@ -13,6 +13,8 @@ function cleanup
 	rm -f ${NVPERMSFILE}
 }
 
+cleanup
+
 trap cleanup EXIT
 
 DEVICES=( $(cat ${CONF} | awk -F: '! /^#/ {print $1}') )
@@ -22,27 +24,39 @@ SCRIPTS=( $(cat ${CONF} | awk -F: '! /^#/ {print $3}') )
 NUM_DEVICES=$(( ${#DEVICES[@]} - 1 ))
 NUM_INDEXES=$(( ${#INDEXES[@]} - 1 ))
 NUM_SCRIPTS=$(( ${#SCRIPTS[@]} - 1 ))
+NUM_UNIQUES=$(( $(for t in ${INDEXES[@]}; do echo $t; done | sort -u | wc -l) - 1 ))
 
 if [ $NUM_SCRIPTS -ne $NUM_DEVICES -o $NUM_DEVICES -ne $NUM_INDEXES ]; then
 	echo "${CONF} parse error" 1>&2
 	exit 1
 fi
 
+if [ $NUM_UNIQUES -ne $NUM_DEVICES ]; then
+	echo "${CONF} parse error, all NVRAM indexes must be different" 1>&2
+	exit 1
+fi
+
 for d in $(seq 0 $NUM_DEVICES); do
 	echo "Generating PCR values for ${DEVICES[$d]}..."
-	${SCRIPTS[$d]} -o ${NVPERMSFILE}
-	if [ $? -ne 0 ]; then
-		echo "${SCRIPTS[$d]} has failed. Aborting."
-		exit 2
+	if [ -x ${SCRIPTS[$d]} ]; then
+		${SCRIPTS[$d]} -o ${NVPERMSFILE}
+		if [ $? -ne 0 ]; then
+			echo "${SCRIPTS[$d]} has failed. Aborting."
+			exit 2
+		fi
 	fi
 
 	echo "Creating new TPM NVRAM secret for ${DEVICES[$d]}..."
-	tpm-luks -c -d ${DEVICES[$d]} -i ${INDEXES[$d]} -p ${NVPERMSFILE}
+	if [ -f ${NVPERMSFILE} ]; then
+		tpm-luks -c -d ${DEVICES[$d]} -i ${INDEXES[$d]} -p ${NVPERMSFILE}
+	else
+		tpm-luks -c -d ${DEVICES[$d]} -i ${INDEXES[$d]}
+	fi
 	if [ $? -ne 0 ]; then
 		echo "tpm-luks has failed. Aborting."
 		exit 3
 	fi
-	rm -f ${NVPERMSFILE}
+	[ -f ${NVPERMSFILE} ] && rm -f ${NVPERMSFILE}
 done
 
 exit 0
diff --git a/tpm-luks/tpm-luks-update b/tpm-luks/tpm-luks-update
--- a/tpm-luks/tpm-luks-update
+++ b/tpm-luks/tpm-luks-update
@@ -12,6 +12,8 @@ function cleanup
 	rm -f ${NVPERMSFILE}
 }
 
+cleanup
+
 trap cleanup EXIT
 
 DEVICES=( $(cat ${CONF} | awk -F: '! /^#/ {print $1}') )
@@ -21,32 +23,44 @@ SCRIPTS=( $(cat ${CONF} | awk -F: '! /^#/ {print $3}') )
 NUM_DEVICES=$(( ${#DEVICES[@]} - 1 ))
 NUM_INDEXES=$(( ${#INDEXES[@]} - 1 ))
 NUM_SCRIPTS=$(( ${#SCRIPTS[@]} - 1 ))
+NUM_UNIQUES=$(( $(for t in ${INDEXES[@]}; do echo $t; done | sort -u | wc -l) - 1 ))
 
-if [ $NUM_SCRIPTS -ne $NUM_DEVICES -o $NUM_SCRIPTS -ne $NUM_INDEXES ]; then
-	echo "${CONF} parse error" 1>&2
-	exit 1
+if [ $NUM_SCRIPTS -ne $NUM_DEVICES -o $NUM_DEVICES -ne $NUM_INDEXES ]; then
+        echo "${CONF} parse error" 1>&2
+        exit 1
+fi
+
+if [ $NUM_UNIQUES -ne $NUM_DEVICES ]; then
+        echo "${CONF} parse error, all NVRAM indexes must be different" 1>&2
+        exit 1
 fi
 
 for d in $(seq 0 $NUM_DEVICES); do
 	echo "Generating PCR values for ${DEVICES[$d]}..."
-	${SCRIPTS[$d]} -o ${NVPERMSFILE}
-	if [ $? -ne 0 ]; then
-		echo "${SCRIPTS[$d]} has failed."
-		continue
+	if [ -x ${SCRIPTS[$d]} ]; then
+		${SCRIPTS[$d]} -o ${NVPERMSFILE}
+		if [ $? -ne 0 ]; then
+			echo "${SCRIPTS[$d]} has failed."
+			continue
+		fi
 	fi
 
 	echo "Migrating TPM NVRAM secret for ${DEVICES[$d]}..."
-	MSG=$(tpm-luks -m -i ${INDEXES[$d]} -d ${DEVICES[$d]} -p ${NVPERMSFILE})
+	if [ -f ${NVPERMSFILE} ]; then
+		MSG=$(tpm-luks -m -i ${INDEXES[$d]} -d ${DEVICES[$d]} -p ${NVPERMSFILE})
+	else
+		MSG=$(tpm-luks -m -i ${INDEXES[$d]} -d ${DEVICES[$d]})
+	fi
 	if [ $? -ne 0 ]; then
 		rm -f ${NVPERMSFILE}
 		continue
 	fi
 	NEWINDEX=$(echo ${MSG} | awk -F " to index " '$1 ~ /Successfully/ { print $2 }')
-	rm -f ${NVPERMSFILE}
+	[ -f ${NVPERMSFILE} ] && rm -f ${NVPERMSFILE}
 
-	echo "# The following line generated by tpm-luks-update" >> ${CONF}
-	echo "${DEVICES[$d]}:${NEWINDEX}:${SCRIPTS[$d]}" >> ${CONF}
-	echo "Success. Updated ${CONF} for index ${INDEXES[$d]}."
+	#echo "# The following line generated by tpm-luks-update" >> ${CONF}
+	#echo "${DEVICES[$d]}:${NEWINDEX}:${SCRIPTS[$d]}" >> ${CONF}
+	#echo "Success. Updated ${CONF} for index ${INDEXES[$d]}."
 done
 
 exit 0
